//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Fan
{
    public Fan()
    {
        this.FanArtists = new HashSet<FanArtist>();
        this.FanGenres = new HashSet<FanGenre>();
        this.FanLogins = new HashSet<FanLogin>();
    }

    public int FanKey { get; set; }
    public string FanName { get; set; }
    public string FanEmail { get; set; }
    public Nullable<System.DateTime> FanDateEntered { get; set; }

    public virtual ICollection<FanArtist> FanArtists { get; set; }
    public virtual ICollection<FanGenre> FanGenres { get; set; }
    public virtual ICollection<FanLogin> FanLogins { get; set; }
}

public partial class FanArtist
{
    public int FanKey { get; set; }
    public int ArtistKey { get; set; }

    public virtual Fan Fan { get; set; }
}

public partial class FanGenre
{
    public int FanKey { get; set; }
    public int GenreKey { get; set; }

    public virtual Fan Fan { get; set; }
}

public partial class FanLogin
{
    public int FanLoginKey { get; set; }
    public Nullable<int> FanKey { get; set; }
    public string FanLoginUserName { get; set; }
    public string FanLoginPasswordPlain { get; set; }
    public int FanLoginRandom { get; set; }
    public byte[] FanLoginHashed { get; set; }
    public Nullable<System.DateTime> FanLoginDateAdded { get; set; }

    public virtual Fan Fan { get; set; }
}

public partial class LoginHistory
{
    public int LoginHistorykey { get; set; }
    public string UserName { get; set; }
    public Nullable<System.DateTime> LoginHistoryDateTime { get; set; }
}
